### PR TITLE
Fix: style Comment section

### LINKED ISSUE #3133: [`Frontend`] : Style comment section
| Status  | Location                                                                                                                                                              | Description                                                         | Image                                                                                                         |
| ------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------- |
| Done | https://github.com/baseplate-admin/CoreProject/blob/58b5158ed09869a9d5036b6450fe974005ef024a/backend/django_core/static_src/components/minor/Comment/Index.svelte#L89 | There should be some form of svg here. Not just a bland thing       |                                                                                                               |
| Done    | https://github.com/baseplate-admin/CoreProject/blob/58b5158ed09869a9d5036b6450fe974005ef024a/backend/django_core/static_src/components/minor/Comment/Index.svelte#L78 | There should be something svg related here, not just a loading text |                                                                                                               |
| Done | https://github.com/baseplate-admin/CoreProject/blob/58b5158ed09869a9d5036b6450fe974005ef024a/backend/django_core/static_src/components/minor/Comment/Index.svelte#L80 | Error state can be better explained                                 | image |

### PR DESCRIPTION
**Pull request by tokitouq**

### CODE REVIEW

File: backend/django_core/static_src/components/minor/Comment/CommentBlockSkeleton.svelte [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+        </div>
+        <div class="skeleton bg-neutral md:h-[0.75vw] md:w-[10vw]" />
+        <div class="flex md:gap-[0.5vw]">
+            <div class="skeleton rounded-full bg-neutral md:h-[0.5vw] md:w-[2vw]" />
+            <div class="skeleton rounded-full bg-neutral md:h-[0.5vw] md:w-[2vw]" />
+        </div>
+        {#if skeleton_count}
+            {#each Array(skeleton_count) as _}
+                <svelte:self />
+            {/each}
```
Comment (baseplate-admin) [inline backend/django_core/static_src/components/minor/Comment/CommentBlockSkeleton.svelte:23]: use `tree`

File: backend/django_core/static_src/components/minor/Comment/Index.svelte [hunk 2]
```diff
@@ -74,11 +75,11 @@
...
 </script>
 
-{#if loading_state === "loading"}
-    Loading..
+{#if loading_state === "loaded"}
+    <CommentSkeleton />
 {:else if loading_state === "error"}
     Something is wrong Error : {@html error}
-{:else if loading_state === "loaded"}
+{:else if loading_state === "loading"}
```
Comment (tokitouq) [inline backend/django_core/static_src/components/minor/Comment/Index.svelte:82]: @baseplate-admin revert these states once you are okay :\

Comment (baseplate-admin) [reply backend/django_core/static_src/components/minor/Comment/Index.svelte:82]: ohh. makes sense
